version: 2
jobs:
  build:
    working_directory: /build/project
    docker:
      - image: quay.io/utilitywarehouse/golang-circleci
    steps:
      - checkout
      - run: go mod download
      - run: golangci-lint run --deadline=2m
      - run: go test -v -race ./...
      - run: go build ./cmd/g2md
